### ISSUE TITLE
DESeq2 normalization

### ISSUE THREAD

**Issue by jc271828** [hbctraining/scRNA-seq_online#102]
Hi!

Thank you for writing the super helpful workbook (https://hbctraining.github.io/scRNA-seq_online/lessons/pseudobulk_DESeq2_scrnaseq.html) on using DESeq2 to do DE analysis with scRNASeq data! I was wondering why in the Top 20 genes' normalized counts plotting step (a little past midway through the workbook, search "top20_sig_df" to locate. It's a gray block of code), the normalized counts are log10 transformed?

I understand that we're plotting "value" in the data frame top20_sig_df. And top20_sig_df is a subset of normalized_counts, with normalized_counts being calculated from normalized_counts <- counts(dds, normalized = TRUE).

I just can't find in DESeq2 vignettes that the normalized counts have been log10 transformed. I thought it was just a normalization using the "size factors". Please correct me if I'm wrong! 

Thank you so much!

Jingxian

**Comment by jc271828** [comment]
Also, is baseMean and the normalized counts on different scales (i.e., one is log-transformed and one is not)?

**Comment by mistrm82** [comment]
Hi @jc271828,

Yes you are right that the normalized counts are log transformed (and so is the value in the baseMean column). 

The log10 transform you are referring to is in the visualization of data. The reason we use `scale_y_continuous(trans = 'log10')` is because gene expression data are heavily skewed on a linear (even after being normalized). There are some genes that are incredibly lowly expressed, and others on the extreme high end. This log10 transform allows us to make the data more symmetrical for visualisation purposes. Note the that the underlying data remains unchanged
