### ISSUE TITLE
add resources

### ISSUE THREAD

**Issue by marypiper** [hbctraining/scRNA-seq_online#50]
https://broadinstitute.github.io/2020_scWorkshop/

? https://nbisweden.github.io/workshop-scRNAseq/schedule.html 

https://azimuth.hubmapconsortium.org/

Single-nucleus and single-cell transcriptomes compared in matched cortical cell types paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6306246/ and https://www.nature.com/articles/s41591-020-0844-1

cellmarker

cellphonedb (https://www.nature.com/articles/s41576-020-00292-x)
spatial transcriptomics
CITE-seq

**Comment by mistrm82** [comment]
Also, eventually add some info/blurb describing snRNA-seq and how does it work differently from scRNA-seq

**Comment by marypiper** [comment]
I have added all links above to workshop schedule page, but need to add spatial and CITE-seq to introduction still

**Comment by jihe-liu** [comment]
Single-nucleus RNA-sequencing (snRNA-seq) analyzes the expression profiles from nuclei, instead of intact cells. In some situations (depending on your research materials and goals), snRNA-seq is the preferred method compared to scRNA-seq. Advantages of snRNA-seq include:
1. Works well with hard-to-isolate samples (for example, adipocytes), as well as frozen tissues;
2. Reduces transcriptional artifacts from the isolation process;
3. Provides less biased cellular coverage;

Typically, less transcripts are detected from the nuclei (~7,000 genes), compared to intact cells (~11,000 genes). In a matched snRNA-seq and scRNA-seq [study](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6306246/), cell types are discriminated effectively with both methods, suggesting that snRNA-seq could still maintain rich transcriptional information. A practical workflow, with both experimental and computational aspects, of scRNA-seq/snRNA-seq is proposed in this [study](https://www.nature.com/articles/s41591-020-0844-1). In particular, for snRNA-seq, the paper suggests testing several protocols for corresponding tissue types, to determine the best approach for the sample.

**Comment by jihe-liu** [comment]
I added some blurbs for snRNA-seq. I am not sure where is the best place to put it, so I leave it as comment here for now @mistrm82

**Comment by mistrm82** [comment]
Add snRNA-seq blurb into a separate doc - include other similar technologies  ie CITE-seq, spatial.

Could be a note as well?

**Comment by mistrm82** [comment]
Tried adding as a note to pre-reading: https://github.com/hbctraining/scRNA-seq_online/pull/63
