### ISSUE TITLE
Using SCT for marker ID

### ISSUE THREAD

**Issue by rkhetani** [hbctraining/scRNA-seq_online#96]
https://search.r-project.org/CRAN/refmans/Seurat/html/PrepSCTFindMarkers.html

Questions in class:
"Why do we set the default assay to "RNA" prior to FeaturePlot? Why do we use NormalizeData prior to FeaturePlot? Wasn't the data normalized in the preparation step? Shouldn't we use SCT assay instead?"

"Again, why do we set the default assay as "RNA" prior to marker identification? Why not "SCT"?"

**Comment by mistrm82** [comment]
In the past, we have used RNA slot because ....

"SCT Pearson residuals themselves are not sparse (contain exclusively non-zero elements), so they take a lot of memory to store. We also find that pearson residuals are challenging to visualize/interpret on either Feature or Violin plots, and therefore RNA is more useful for this."

.."If you performing DE using SCT on the scale.data slot it would only test differences in variable genes. "

https://github.com/satijalab/seurat/issues/2180

**Comment by mistrm82** [comment]
But now with Seurat 4.0 we can "PrepSCTFindmarkers" so maybe we should we doing this?

`FindMarkers(immune.combined.sct, assay = "SCT", ident.1 = "B_STIM", ident.2 = "B_CTRL",
    verbose = FALSE)`

**Comment by mistrm82** [comment]
added a note about why we don't use sct and what the values represent. didn't add anything about prepSCTFindMarkers since we have never used it
